### ISSUE TITLE
Numpy or Dask image array support

### ISSUE THREAD

**Issue by rjesud** [NHPatterson/wsireg#22]
Is it possible to provide a numpy or dask array as input for `reg_graph.add_modality()`

My usecase:
I would like to register an H&E to an IF set.  The H&E is coming from the same section. So, I would like to use the nuclear information to register the images. To do this, I would execute a script to do stain separation on the H&E, providing me with an isolated hematoxylin channel. There are many methods but here is one from [scikit image as an example](https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_ihc_color_separation.html) . I would then register this hematoxylin "channel" (as numpy or dask array) to the DAPI of the IF. Then I would take the tranformation matrix and apply it to the H&E ometiff. 

Is this complicating things? Is there an easier way to register a sequentially stained H&E by nuclear info?

**Comment by NHPatterson** [comment]
No problem at all, `add_modality` allows you pass in zarr, dask, and numpy arrays as well as file paths. 

Below I took your previous script and make a fake numpy array. 

```python
from wsireg.wsireg2d import WsiReg2D
import os

os.chdir('/blah/ometiff_imagefolder/')

# initialize registration graph
reg_graph = WsiReg2D("my_reg_project", "./project_folder2")

cool_array = np.zeros((2048,2048), dtype=np.uint8)

# add registration images (modalities)
reg_graph.add_modality(
    "modality_fl1",
    cool_array,
    image_res=0.325,
    channel_names=["DAPI", "FITC", "Cy3","Cy5","Cy7","CFP"],
    channel_colors=["blue", "green", "red","yellow","purple","orange"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": True,
    },
)

```

Then there is also the concept of an `attachment_modality` in `wsireg`. This is a modality that is transformed along a registration path, BUT not itself registered. So while you will use the deconvoluted nuclei image to do the registration.. the transformation will be applied to the H&E.
```python
## arguments
# attached modality
# name of modality
# filepath to modality
# image res of modality
reg_graph.add_attachment_modality(
    "modality_fl1", "HE_full", "he_filepath.ome.tiff", image_res=0.325
)
```

Sorry, the lack of tutorial/docs here is not helping. work in progress.

**Comment by NHPatterson** [comment]
Sorry you may want to pull down a newer version, I discovered a problematic bit of code I didn't forsee when examining the attachment modality code, but it is fixed now, so please let try and let me know. Almost there..

**Comment by NHPatterson** [comment]
@rjesud Can you confirm this works on your side? I would like to close this issue.

**Comment by rjesud** [comment]
@NHPatterson I pulled down from the git repo yesterday. I have version 0.3.0

I receive the following error:
  reg_graph.add_attachment_modality("hematoxylin", "HE_full", "he.ome.tiff", image_res=0.5)
AttributeError: 'WsiReg2D' object has no attribute 'add_attachment_modality'

**Comment by rjesud** [comment]
scratch that. I see insource-code it is named `reg_graph.add_attachment_images()`. Testing now...

**Comment by rjesud** [comment]
@NHPatterson , Seems to run into an issue at save_transformations() step:
`Traceback (most recent call last):
  File "wsireg1_he.py", line 62, in <module>
    reg_graph.save_transformations()
  File "/gstore/home/jesudasr/.conda/envs/wsireg/lib/python3.7/site-packages/wsireg/wsireg2d.py", line 1172, in save_transformations
    final_modality = self.reg_paths[attachment_modality][-1]
KeyError: 'modality_fl2'`

My code:
```
from wsireg.wsireg2d import WsiReg2D
import os
from tifffile import imread
from skimage.color import rgb2hed, hed2rgb
import matplotlib.pyplot as plt
from skimage import data
import numpy as np

os.chdir('/MYDIR/')

he=imread("my_HE.ome.tiff")
he=np.transpose(he,(1,2,0)) #scikit image wants image in XYC order

sep_he = rgb2hed(he) #stain seperation
hematoxylin=sep_he[:,:,0] #take hematoxylin only

hematoxylin=np.expand_dims(hematoxylin, axis=0) #create a channel dim to be akin to IF image

# initialize registration graph
os.mkdir('./alignment_output')
reg_graph = WsiReg2D("my_reg_project", './alignment_output')

# add registration images (modalities)
reg_graph.add_modality(
    "modality_fl1",
    "my_IF.ome.tiff",
    image_res=0.325,
    channel_names=["DAPI", "CH2", "CH3, "CH4", "CH5", "CH6"],
    channel_colors=["blue", "green", "red","yellow","purple","orange"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": None,
    },
)

reg_graph.add_modality(
    "modality_fl2",
    hematoxylin,
    image_res=0.5,
    channel_names=["Hematoxylin"],
    channel_colors=["blue"],
    prepro_dict={
        "image_type": "FL",
        "ch_indices": [0],
        "as_uint8": True,
        "contrast_enhance": None,
    },
)

reg_graph.add_reg_path(
    "modality_fl1",
    "modality_fl2",
    thru_modality=None,
    reg_params=["rigid","affine"],
)

reg_graph.add_attachment_images("modality_fl2", "HE_full", "my_HE.ome.tiff", image_res=0.5)
reg_graph.add_merge_modalities("multicycle",["modality_fl1","modality_fl2"])
reg_graph.register_images()
reg_graph.save_transformations()
reg_graph.transform_images(file_writer="ome.tiff")
```

**Comment by NHPatterson** [comment]
Apologies, this is a silly bug that I fixed. Can you pull down the latest version of the repo? or re-install from pip, as I've deployed the latest version.

**Comment by rjesud** [comment]
I pulled down the latest version of the repo. Unfortunately, the error persists.

```
Traceback (most recent call last):
  File "wsireg1_he.py", line 62, in <module>
    reg_graph.save_transformations()
  File "/gstore/home/jesudasr/.conda/envs/wsireg/lib/python3.7/site-packages/wsireg/wsireg2d.py", line 1172, in save_transformations
    final_modality = self.reg_paths[attachment_modality][-1]
KeyError: 'modality_fl2'
```

**Comment by NHPatterson** [comment]
@rjesud I was able to locate the cause of the error and fix it and added appropriate tests. Can you try with the latest, thanks for your help.

**Comment by rjesud** [comment]
Seems to be something tricky. I still encounter the same exact error. I pip uninstalled wsireg, cleared my conda cache, pip installed from wsireg git repo and re-ran the code. Same error.

**Comment by rjesud** [comment]
o, maybe i need to clear pip cache... testing

**Comment by NHPatterson** [comment]
Oh sorry, I haven't deployed the fix yet to PyPI. if you can clone the repo and install from there it should work, or install the repo from pip:

`pip install git+https://github.com/nhpatterson/wsireg`

**Comment by rjesud** [comment]
Sorry to say. Same outcome. I cleared all cache and ran pip install from git as outlined. I have done this for the other bug fixes. Not sure why the error persists. 

r

**Comment by NHPatterson** [comment]
Ah... on a second look I think the problem is the set up in the registration.

This is the alignment set up:
```python 
# modality_fl1 is source
# modality_fl2 is target
reg_graph.add_reg_path(
    "modality_fl1",
    "modality_fl2",
    thru_modality=None,
    reg_params=["rigid","affine"],
)
```
This aligns the IF (fl1) to the deconvoluted H&E (fl2), and you are attaching the full H&E to a modality that isn't being transformed. The fact that it is failing is a problem still though, it should catch this and warn.

If you change the path it should work:
```python
reg_graph.add_reg_path(
    "modality_fl2",
    "modality_fl1",
    thru_modality=None,
    reg_params=["rigid","affine"],
)
```

If you use your original case, you don't really need to attach the H&E, since the final IF image will be registered to H&E. It all depends on which direction you want to go for the final image. H&E -> IF or IF -> H&E.

**Comment by rjesud** [comment]
Yes! This solved the issue. Thank you very much. I can now confirm this H&E deconvolution workflow is feasible.

r

**Comment by rjesud** [comment]
small comment - deconvolved image needs to be converted to same dtype of modality1 for merging to execute.

**Comment by NHPatterson** [comment]
@rjesud Glad it worked. I hope the registration worked, I've never tried this approach but it seems smart. as for mixing dtypes, I'm going to work on a fix for that. For now, it should error, but I will put it in the queue as an enhancement
